/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Proyecto_inicial_aplicacion_local_acceso_SGBD;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
